import type { Metadata } from "next";
import "./globals.css";
import NextAuthSessionProviders from "@/providers/NextAuthSessionProviders";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "sonner";
import { cn } from "@/lib/utils";
import Main from "@/components/Main";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("h-dvh w-full overflow-hidden")}>
        <NextAuthSessionProviders>
          <ThemeProvider>
            <Main
              id="main"
              className={cn(
                `main grid grid-rows-[auto_1fr_auto]`,
                `h-dvh max-h-dvh w-full overflow-y-auto`
              )}
            >
              <NavBar />
              <div className={"flex flex-col py-2 px-2 md:px-10"}>
                {children}
              </div>
              <Footer />
            </Main>
            <Toaster richColors={true} />
          </ThemeProvider>
        </NextAuthSessionProviders>
      </body>
    </html>
  );
}
